main/urls.py
app_name="main"

from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:id>/', views.details, name="details"),
    path('addmovies/', views.add_movies, name="add_movies"),
    path('addreview/<int:id>', views.add_review, name='add_review'),

]

moviereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Movie(models.Model):
    # Fields for the movie table
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=300)
    release_date = models.DateField()
    description = models.TextField(max_length=5000)
    rating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000, null=True)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.movie.name

main/forms.py
from django import forms
from .models import *

#movie add form

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'release_date', 'description', 'image')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment", "rating")

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.shortcuts import render, redirect, get_object_or_404

from .forms import *
# Create your views here.
def home(request):
    query = request.GET.get("title")
    allMovies = None
    if query:
        allMovies = Movie.objects.filter(name__icontains=query)
    else:
        allMovies = Movie.objects.all()   # select * from movies
    #can use ,context dictionary instead {'movies': allMovies}
    return render(request, 'main/index.html', {'movies': allMovies}) #got error here, instead of using dictionary write in this way


# detail page
def details(request, id):
    movie = Movie.objects.get(id=id)
    # Retrieve reviews for the specific movie
    reviews = Review.objects.filter(movie=id).order_by("-comment")
    average = reviews.aggregate()
    return render(request, 'main/details.html', {'movie': movie, 'reviews': reviews})

# add movies to database
def add_movies(request):
    if request.method == "POST":
        form = MovieForm(request.POST or None)
        # check if the form is valid
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:  # If it's not a POST request, render the empty form
        form = MovieForm()
        return render(request, 'main/addmovies.html', {"form": form})

#review
def add_review(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == "POST":
        form = ReviewForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.movie = movie
            data.save()
            return redirect("main:details", id=id)
    else:
        form = ReviewForm()
        return render(request, 'main/details.html', {"movie": movie, "form": form})

main/templates/main/addmovies.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <div class="card">
    <div class="card-content">
      <h3 class="text-center">Add Movies</h3>
      <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy}}
        <input type="submit" value="Add Movie">
      </form>
    </div>
  </div>

</div>

{% endblock %}

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-qk2Xx8sw1/fFWjZvIurq1nOnpc+xNMKNq1Z+KPIoJDebxKtPIyOuxAFVtDT8Fp7lLr0sPHo5KtxX4PlqExZNg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        body{
            background-image: url("{% static 'img/background.jpg' %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;

        }
        a{
        text-align: center;
        display: block;
        color: oceanblue;
        }
        a:link {
            color: black;
            background-color: transparent;
            text-decoration: none;
        }
        #cardstyle{


        .card {
            margin-right: auto;
            margin-left: auto;
            width: 250px;
            box-shadow: 0 15px 25px rgba(129, 124, 124, 0.2);
            height: 300px;
            border-radius: 5px;
            backdrop-filter: blur(50px);
            background-color: ;
            padding: 10px;
            text-align: center;
        }

        .card img {
            height: 60%;
        }
        .tab-space {
            margin-center: 20px;
        }

        }

    </style>

  </head>
  <body>
<!-- Navigation Bar Starts Here -->
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #001F7B">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}"> <img src="{% static 'img/logo.png' %}" style="width:150px;height:50px"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:add_movies' %}">Add Movies</a>
                </li>
            </ul>
            <form class="d-flex" method="GET" action="{% url 'main:home' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="title">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="navbar-text ms-2">
                <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-sign-out-alt fa-sm"></i>
                </button>
            </div>
            </div>
        </div>
    </div>
</nav>

    {% block content%}

    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<style>
    .tab-space {
        margin-right: 20px;
    }
    .movie-container {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column; /* Place items in a column */
    }
    .movie-image {
        height: 150px; /* Set the height as per your preference */
        object-fit: cover;
        margin-top: 10px; /* Add some space between the YouTube player and the image */
    }
    .youtube-player {
        flex: 1; /* To occupy equal space with the image */
        margin-top: 10px;
    }
</style>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="movie-container">
                            <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid movie-image">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="movie-container">
                            <div class="youtube-player">
                                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ movie.trailer_id }}"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h1 class="card-title text-center">{{ movie.name }}</h1>
                    <div class="rating-container" align="center">
                        <b>Rating:  {{movie.rating}} </b>
                    </div>
                    <hr>
                    <p class="card-text"><b>Cast: </b>{{ movie.cast }}</p>
                    <hr>
                    <p class="card-text"><b>Description: </b>{{ movie.description }}</p>
                    <hr>
                    <p class="card-text"><i>Release Date: {{ movie.release_date }}</i></p>
                    <hr>
                    {% if reviewed %}
                         <p>You have already reviewed this movie.</p>
                    {% else %}
                    <h2>Ratings and Reviews</h2>
                    <form action="{% url 'main:add_review' movie.id %}" method="POST" >
                        {% csrf_token %}
                        <label for="comment">Review</label>
                        <textarea name="comment" id="comment" cols="30" rows="5" class="form-control" required></textarea>
                        <label for="rating">Rating</label>
                        <input type="number" name="rating" id="rating" class="form-control" min="1" max="10" step="0.1" required>
                        </br>
                        <button type="submit" class="btn btn-primary">Submit Review</button>
                    </form>
                    {% endif %}
                    <div class="mt-4">
                        {% for review in reviews %}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h5 class="card-title">{{ review.user }}</h5>
                                    <p class="card-text">{{ review.comment }}</p>
                                    <p class="card-text"><b>Rating: {{ review.rating }}</b></p>
                                </div>
                            </div>
                        {% endfor %}

                        {% if not reviews %}
                            <p>No ratings and reviews yet.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}

<style>
    .tab-space {
        margin-right: 20px;
    }
    .movie-container {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column; /* Place items in a column */
    }
    .movie-image {
        width: 200px; /* Set the width as per your preference */
        height: 300px; /* Set the height as per your preference */
        object-fit: cover; /* Maintain aspect ratio and crop as needed */
        margin-top: 10px; /* Add some space between the YouTube player and the image */
    }
    .youtube-player {
        flex: 1; /* To occupy equal space with the image */
    }
    .rating-container {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .movie-details {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 20px; /* Add margin between the movie image and details */
    }
    .release-year, .description {
        width: 100%;
        padding: 5px;
        border: 1px solid #ccc;
        text-align: center;
        margin-bottom: 5px;
        word-wrap: break-word; /* To wrap long content */
    }
    .movie-name {
        height: 50px; /* Set a fixed height for the movie name heading */
        width: 100%; /* Allow the name box to fill the available width */
        overflow: ellipsis; /* Hide any overflowing text */
        text-overflow: ellipsis; /* Show ellipsis (...) for long names */
        white-space: nowrap; /* Prevent line breaks */
        font-size: 100%;
    }
</style>

<div class="container mt-5" align="center">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        {% for movie in movies %}
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body" align="center">
                                    <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid tab-space movie-image" width="200" height="300">
                                    <b class="movie-name"><a href="{% url 'main:details' movie.id %}" class="text-center">{{ movie.name }}</a></b>

                                    <div class="rating-container">
                                        <b>Rating:  {{movie.rating}} </b>
                                    </div>
                                    <div class="movie-details">
                                        <div class="release-year">
                                            <p><b>Release Year: {{ movie.release_date|date:'Y' }}</b></p>
                                        </div>
                                        <div class="description">
                                            <p>{{ movie.description|truncatechars:100 }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}